# constants.py
LANGUAGE, MENU, PACKAGE, DEPARTURE, COUNTRY,DESTINATION,TYPE ,DATE_SELECTION, DURATION_SELECTION, ROOM_SELECTION ,NOTIFY ,MONTH_SELECTION ,FLEXIBLE_SELECTION,TYPING_DURATION  = range(14)
